# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wx-PdfDocument
version:      0.05
version_from: lib/Wx/PdfDocument.pm
installdirs:  site
requires:
    Wx:                            0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
